name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: 8.0

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 8.0
          configuration: ./phpunit.ci.xml
          php_extensions: xdebug
        env:
          XDEBUG_MODE: coverage

      - name: Swagger and coverage report to public
        if: always()
        run: |
          composer swagger
          sudo mv public/swagger docs/swagger
          sudo mv tests/_reports docs/coverage

      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          push_badge: false
          coverage_badge_path: 'docs/coverage.svg'
          report_type: html
          report: docs/coverage/index.html

      - name: Deploy documentation
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./docs
